version: "3.5"

services:

  keycloak:
    image: keycloak:3.4.4.Snapshot
    build:
      context: .
    container_name: keycloak-server
    environment:
      JBOSS_USER: jboss
      JBOSS_PASSWORD: jboss00#
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      POSTGRES_ADDR: postgres
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - postgres
    networks:
      - backend-nw
      - database-nw

  postgres:
    image: postgres:9.6-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: postgres
    volumes:
      - keycloack-db:/var/lib/postgresql/data
    networks:
      database-nw:
        aliases:
          - postgres
  
networks: 
  database-nw:
  backend-nw:

volumes:
  keycloack-db: